eclass/ui-kit

src/index.ts
=> feat(theme): export theme to the library

package-lock.json, src/atoms/Label/Label.stories.tsx, src/atoms/Label/Label.tsx, src/atoms/Progress/Progress.stories.tsx, src/atoms/Progress/Progress.tsx, src/atoms/Ripples/Ripples.stories.tsx, src/atoms/Ripples/Ripples.tsx, src/components/TestVars.tsx, src/index.ts, src/organisms/CourseList/CourseBox.tsx, src/organisms/CourseList/CourseList.stories.tsx, src/organisms/CourseList/CourseList.tsx, src/organisms/CourseList/components/DateStatus.tsx, src/organisms/CourseList/components/Footer.tsx, src/organisms/CourseList/components/Header.tsx, src/organisms/CourseList/components/IconSelection.tsx, src/organisms/CourseList/components/Section.tsx, src/organisms/CourseList/dataFake.ts, src/organisms/CourseList/types.d.ts
- agrego `stories` a `Label` `Ripples` `Progress` 
- conecto `CourseList` con los types de `API` + `stories`
=> feat(atoms): stories, courselist type api

.eslintrc.json, .storybook/main.js, jest.config.js, package-lock.json, package.json, src/atoms/Colors/Colors.tsx, src/atoms/Icons/Base.tsx, src/atoms/Label/Label.stories.tsx, src/atoms/Label/Label.tsx, src/atoms/Progress/Progress.tsx, src/index.ts, src/main.tsx, src/organisms/CourseList/CourseBox.tsx, src/organisms/CourseList/CourseList.tsx, src/organisms/CourseList/components/DateStatus.tsx, src/organisms/CourseList/components/Footer.tsx, src/organisms/CourseList/components/Header.tsx, src/organisms/CourseList/components/IconSelection.tsx, src/organisms/CourseList/components/Section.tsx, src/organisms/CourseList/types.d.ts, src/stories/DocsContainer.tsx, tsconfig.json, tsconfig.types.json, vite.config.ts
Se agrega alias en la ruta del proyecto, configurados en los diferentes lugares. 
- Test
- Storybook
- Codigo
- Types
closed #108 
closed #104
=> chore: add alias to remove relatives paths

src/organisms/CourseList/CourseBox.tsx, src/organisms/CourseList/components/Footer.tsx, src/organisms/CourseList/index.ts, src/organisms/CourseList/types.d.ts, src/organisms/CourseList/utils/dataFake.ts, src/organisms/CourseList/utils/index.ts, src/organisms/CourseList/utils/isCourseActive.ts, src/organisms/CourseList/utils/maxWidthCoursesList.ts
Solo se estaba validando si el curso estaba activo para que este diera la opción de acceder a él, el  problema es que los que tienen el curso cargado con otro perfil (editor) no podían acceder para revisar el contenido del curso. 
Por lo que se opto por agregar a la validación que si esta cargado con `Profile` distinto al id alumno (4), este pueda acceder al curso independiente si el curso aún no esta disponible.
=> fix(courselist): acceder al curso

src/molecules/Buttons/Btn.tsx, src/molecules/Buttons/BtnPrimary.tsx, src/molecules/Buttons/BtnSecondary.tsx, src/molecules/Buttons/BtnTertiary.tsx
Se agrega el prop de id a los botones primario, secundario y terciario. Además, al terciario también se agregan los props de type y tabIndex.
[PTA-1529](https://eclass.atlassian.net/browse/PTA-1529)
=> fix(molecules): nuevos props botones

src/molecules/Buttons/BtnLink.stories.tsx, src/molecules/Buttons/BtnLink.tsx
Creación de componente de botón tipo link, para la sección de "Mi perfil".
[PTA-1529](https://eclass.atlassian.net/browse/PTA-1529)
=> feat(molecules): botón link sin ícono para sección 'mi perfil'

src/molecules/Buttons/Btn.tsx
Se agrega una altura mínima determinada dependiendo de si el botón es tamaño regular o small.
=> fix(base-btn): altura definida para botones regulares y small

src/molecules/Buttons/BtnTertiary.tsx
Inclusión de media queries para el efecto hover en botón terciario, que no funcionaba correctamente en formato móvil.
[PTA-1529](https://eclass.atlassian.net/browse/PTA-1529)
=> fix(tertiary-btn): media query hover

src/organisms/CourseList/components/CourseStatus.tsx, src/organisms/CourseList/components/Section.tsx, src/organisms/CourseList/index.ts
Exporto componente que muestra el estado en el que se encuentra el avance del curso
=> feat(organisms): exporto componente que da el estado del curso

src/molecules/Tooltip/NewTooltip.tsx
- Modificación del ancho máximo default del tooltip de 170px a 200px
- Inclusión de maxWidth como prop del componente para que pueda modificarse si es necesario
=> fix(tooltip): ajuste de ancho máximo

package-lock.json, package.json
Actualizo tipos de la API ya que en la plataforma me esta dando un error al desplegar
=> fix(update): actualizado types de la api

src/organisms/CourseList/Boxes/BoxImage.tsx
Corrección de margen bottom en textos de caja imagen
=> fix(imagebox): margen cero para textos

src/organisms/CourseList/types.d.ts
Descripción de qué argumento se recibe en cada prop del componente CourseList para facilitar su implementación.
=> fix(courselist): descripción de props

src/organisms/Alerts/Alert.tsx, src/organisms/Alerts/FlashNotification.tsx, src/organisms/Alerts/types.d.ts
- Modificación de ancho alerta embebida
- Modificación de diagramado de botón en mobile y escritorio
- Reemplazo de margins por gap
- Mejor validación de botones según tipo
- Inclusión de handleClick
=> fix(alerts): corrección ancho y botón en mobile

src/atoms/Icons/Alerts/InfoWhite.tsx, src/organisms/Alerts/Alert.test.tsx, src/organisms/Alerts/Alert.tsx
Unit test para el componente de Alert
=> feat(alerts): test

.github/workflows/nodejs.yml, package-lock.json
=> feat(docu): deploy documentation

.github/workflows/nodejs.yml, package-lock.json, package.json
=> Documentation

.github/workflows/nodejs.yml
=> feat(yml): configuration jobs to deploy gh-pages

index.html
Correccion de dependencias en produccion
=> feat(doc): correction dependencies

.github/workflows/nodejs.yml, package-lock.json
Se agrega cambio para que no ocupe el package-lock en produccion y lo regenere desde 0 en la maquina.
=> feat(package): remove package-lock in machine and regenerate

src/documentation/pages/Molecules/Buttons.tsx, src/molecules/Buttons/BtnTertiary.tsx
Se agrega props que recibe un icono custom, por si los que se liberaron no cumplen con lo solicitado
=> Button tertiary con icono custom

src/organisms/Alerts/Alert.tsx, src/organisms/Alerts/types.d.ts
- Inclusión de parámetro fullWidth para alertas dentro de contenedores que deban ocupar el 100% de ancho.
- Corrección de alineación de icono.
=> fix(PDYE-408-alerts): corrección de estilo componente alerta

package-lock.json, package.json, src/documentation/components/Code.tsx, src/documentation/components/Layout.tsx, src/documentation/components/Organisms/ModalAlertDoc/ModalAlertDoc.tsx, src/documentation/components/Organisms/index.ts, src/documentation/pages/Organisms/Alerts.tsx, src/documentation/pages/Organisms/ModalAlert.tsx, src/documentation/utils/routes.tsx, src/molecules/Buttons/BtnLink.tsx, src/organisms/Alerts/Alert.tsx, src/organisms/Alerts/types.d.ts, src/organisms/ModalAlert/ModalAlert.tsx, src/organisms/ModalAlert/index.ts, src/organisms/ModalAlert/types.d.ts, src/organisms/index.ts
Se agrega la alerta y modal correspondiente para proctoring.
=> feat(PDYE-598): se agrega alert y modal con documentacion uikit

src/organisms/Alerts/Alert.tsx
Se corrige el extra párrafo que se había agregado.
=> fix(proctoring): correction paragraph

src/organisms/ModalAlert/ModalAlert.tsx
correccion de resolucion de modal forzada.
=> fix(modal): correction resolution of modal

src/organisms/ModalAlert/ModalAlert.tsx
se agregan detalles de correccion a la ora de embeber modal que falla.
=> fix(modal): correction problems with props modal general

src/organisms/ModalAlert/ModalAlert.tsx
se corrige margenes que se eliminan forzadamente al importar
=> fix(modal): detail modal with margin in topline

src/organisms/ModalAlert/ModalAlert.tsx
se agregan correcciones para que el modal sea visible correctamente en v8
=> fix(modal): update changes correction css

src/organisms/ModalAlert/ModalAlert.tsx
se devuelve cambio de centrado de modal alert
=> fix(modal): details of get type

src/organisms/ModalAlert/ModalAlert.tsx
se ajusta el ancho del boton basado en el Box padre y el evento de este, asi ocupa el ancho del espacio de boton del modal.
=> fix(modal): details of widh button modal

src/Playground.tsx, src/main.tsx, src/molecules/Buttons/BtnTertiary.tsx
Soluciono cuando no quiero iconos en el btn terciario y los iconos no cambian de color al hover
=> fix(molecule): btn tertiary icon

index.html, src/documentation/pages/Organisms/Events.tsx, src/documentation/pages/Organisms/Resources.tsx, src/organisms/Events/Eventos.tsx, src/organisms/Events/Events.tsx, src/organisms/Events/EventsTypes.d.ts, src/organisms/Events/Icons/Calendar.tsx, src/organisms/Events/Icons/Clock.tsx, src/organisms/Events/Icons/index.ts, src/organisms/Events/TypeBox/LargeBox.tsx, src/organisms/Events/TypeBox/SmallBox.tsx, src/organisms/Events/TypeBox/index.ts, src/organisms/Events/index.ts, src/organisms/Resources/Resources.tsx
Se agrega caja eventos y se hace ajuste para el comportamiento de los links en los recursos.
=> feat(PCV-1094): se agrega la caja eventos

src/documentation/pages/Molecules/UserWay.tsx
=> fix(userway): documentacion

src/atoms/Icons/Accessibility.tsx, src/documentation/pages/Molecules/UserWay.tsx, src/molecules/UserWay/UserWay.tsx
Se quita el prop de accountId y se deja la cuenta de Rod como predeterminada.
=> fix(userway): se deja id fijo

src/atoms/Icons/Accessibility.tsx, src/documentation/pages/Molecules/UserWay.tsx, src/molecules/UserWay/UserWay.tsx
Actualización de componente UserWay que mantiene estilos base pero modifica su comportamiento. El botón ya no implementa el script del widget, sino que activa otro botón ubicado en el archivo index.html a través de una función trigger.
=> fix(PDYE-974): nuevo botón userway

src/organisms/Events/TypeBox/LargeBox.tsx
Se remueve el gradient en la caja eventos grande
=> fix(events): se remueve gradiente para caja eventos grandes

src/documentation/pages/Organisms/CourseList.tsx, src/organisms/CourseList/Boxes/BoxImage.tsx, src/organisms/CourseList/Boxes/BoxTraditional.tsx, src/organisms/CourseList/Boxes/Boxes.tsx, src/organisms/CourseList/CourseList.tsx, src/organisms/CourseList/components/Header.tsx, src/organisms/CourseList/types.d.ts, src/organisms/CourseList/utils/dataFake.ts
Se agrega la caja curso funcionando.
=> feat(PDYE-994): se agrega caja curso futura con validaciones

src/organisms/CourseList/Boxes/Boxes.tsx, src/organisms/CourseList/types.d.ts
=> fix(coursefuture): se corrige el type del course

src/organisms/CourseList/components/Header.tsx
Se corrige validacion del nuevo background
=> fix(coursefuture): se agrega link directo de image en url para box

src/organisms/CourseList/components/Header.tsx
Se corrige el z-index que afecta el before del courselist
=> fix(coursefuture): se corrige zindex que no funciona en cv

package-lock.json, src/organisms/Calendar/Dropdown/CalendarDropdown.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/CalendarDropdownContainer.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/Empty.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/Events.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/GoToCalendar.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/Header.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Icons/CalendarButtonIcon.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Icons/NoEventsIcon.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/services/parseEvents.ts, src/organisms/Calendar/Dropdown/types.d.ts, src/organisms/Calendar/EventsList/EventsList.tsx, src/organisms/Calendar/EventsList/NotificationIcon.tsx
Modificaciones de estilo que corrigen desajustes visuales en la implementación del componente de menú dropdown calendario en v8 y cv.
=> fix(PDYE-1136): ajustes visuales menu dropdown

src/organisms/Calendar/Dropdown/CalendarDropdown/CalendarDropdownContainer.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/Events.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/EventsGroup.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/GoToCalendar.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/Header.tsx, src/organisms/Calendar/Dropdown/types.d.ts, src/organisms/Calendar/EventsList/EventsList.tsx, src/organisms/Calendar/EventsList/NotificationIcon.tsx
- Revisión y corrección types
- Separación de componentes Events y EventsGroup
- Ajuste función que oculta el fondo en formato mobile para que se ejecute sólo en una dimensión determinada y cuando el botón cumpla la función de desplegar el menú. 
- Hover botón
- Cambio de nombre clase ícono notificación
- Borrado código comentado
- Se agrega pseudo elemento al componente que envuelve el menu para que genere el ícono de notificación en reemplazo del svg que estaba dentro de GoToCalendar
=> fix(PDYE-1136): orden archivos y correcciones estilo

src/organisms/Calendar/Dropdown/CalendarDropdown/CalendarDropdownContainer.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/GoToCalendar.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/Header.tsx
- Ajustes que corrigen distorsión del botón en iphone.
- Paso de flecha menu a pseudo elemento.
=> fix(PDYE-1136): boton iphone y flecha

jest.config.js, tsconfig.json
Se agrega maping de los archivos types para al exportacion, abriendo compatibilidad con node18+
=> fix(): se corrige la exportacion de types para versiones futuras

package.json
Se corrige exportacion de package para types
=> fix(): se agrega export de types en package

package-lock.json, package.json
Prueba para compilarlo en react19
=> fix(): se agrega compatibilidad para react19 prueba1

package-lock.json, src/index.ts, src/organisms/Events/index.ts, src/organisms/ModalAlert/index.ts
Prueba de exports de la app. TODO pruebas
=> fix(): correccion de exports para ui kit

package.json, vite.config.ts
=> fix(): se hace reduccin del bundle probando la configuracion sugerida

src/organisms/Calendar/EventsList/EventsList.tsx
Estilos para caja evento en vista mobile
=> fix(PDYE-1230): evento mobile

src/organisms/Calendar/Dropdown/CalendarDropdown/Components/Events.tsx, src/organisms/Calendar/EventsList/EventsList.tsx
Se modifica versión mobile de comoponente evento
Se cambia botón de dropdown calendario a primario
=> fix(PDYE-1230): correcciones version mobile evento

src/organisms/Calendar/EventsList/EventsList.tsx
- Cambio de alineación de ícono de notificación dentro de componente de evento.
- Ajuste de ancho de título de evento para que no desplace el ícono cuando es muy largo.
=> fix(PDYE-1288): ajuste alineacion notificacion evento

src/molecules/NavBarButtons/NavBarButton.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/CalendarDropdownContainer.tsx, src/organisms/Calendar/Dropdown/CalendarDropdown/Components/GoToCalendar.tsx
- Se elimina tooltip del botón del dropdown calendario
- Se agrega prop 'as' a componente para botones de la barra de navegación
=> fix(PDYE-1297): se quita tooltip

src/organisms/Calendar/Dropdown/CalendarDropdown/CalendarDropdownContainer.tsx
Ajuste posición de ícono de notificación que se había desplazado con la inclusión de texto en el botón.
=> fix(PDYE-1298): posicion icono notificacion calendario

src/molecules/NavBarButtons/NavBarButton.tsx
Corrige texto de botón que se desalineaba en safari
=> fix(PDYE-1328): alineacion de items botones barra

src/organisms/Modals/Modal/Modal.test.tsx, src/organisms/Modals/Modal/Modal.tsx, src/organisms/Modals/ModalAlert/ModalAlert.tsx
Auto focus false por default para componente Modal
=> fix(PDYE-1395): auto focus false para modal base

src/organisms/CourseList/Boxes/BoxImage.tsx, src/organisms/CourseList/Boxes/BoxTraditional.tsx
Cambios en atributos de focus en componentes BoxTraditional y BoxImage.
=> fix(PDYE-1434): de focusWithin a focusVisible CourseList

src/organisms/Events/TypeBox/LargeBox.tsx, src/organisms/Events/TypeBox/SmallBox.tsx, src/organisms/Resources/Resources.tsx
Se agrega focus visible a los componentes eventos y recursos, archivos SmallBox, LargeBox y Resources.
=> fix(PDYE-1435): focus recursos y eventos
